### ISSUE TITLE
No loader is defined for .ttf files

### ISSUE THREAD

**Issue by mckravchyk** [glromeo/esbuild-sass-plugin#184]
I have a font-face definition

```scss
@font-face {
  font-family: 'NotoSans';
  font-style: normal;
  font-weight: 400;
  src: url('../assets/fonts/NotoSans400.ttf') format('truetype');
}
```

It looks like it's trying to resolve it, giving an error: "No loader is defined for .ttf files" Obviously, I do not want to load those files, just pass the url statement to the output CSS. Is there a way to make this work? Thanks!
